CREATE TABLE [dbo].[DFIE_CargadeArchivoAccionesDeFormacion] (
    [idAccion]                      VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [nombre_accion]                 NVARCHAR (MAX) DEFAULT (' ') NOT NULL,
    [nombre_tipo]                   VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [dirigido]                      VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [nombre_dirigido]               VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [idGrupo]                       VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [nombre_sedeCorto]              VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [nombre_unidadResponsableCorto] VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [fechaInicio]                   VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [fechaTermino]                  VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [diasImpartidos]                VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [fechaEvaluacion]               VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [horaInicio]                    VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [horaTermino]                   VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [instructores]                  NVARCHAR (MAX) DEFAULT (' ') NOT NULL,
    [cupo]                          VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [aula]                          VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [nombre_modalidad]              VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [duracion]                      VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [atendidos_total]               VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [atendidos_mujeres]             VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [atendidos_hombres]             VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [acreditados_total]             VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [acreditados_mujeres]           VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [acreditados_hombres]           VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [acreditados_mujeres_tc]        VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [acreditados_hombres_tc]        VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [acreditados_tc]                VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [nombre_estado]                 VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [estado]                        VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [idUnidad]                      VARCHAR (255)  DEFAULT (' ') NOT NULL,
    [orden_unidad]                  VARCHAR (255)  DEFAULT (' ') NOT NULL
);

