CREATE TABLE [dbo].[FAES_IndicadoresExtra] (
    [ID_FAES_IndicadoresExtra] INT           IDENTITY (1, 1) NOT NULL,
    [EjeFundamental]           VARCHAR (255) DEFAULT (' ') NOT NULL,
    [ProjectoInstitucional]    VARCHAR (255) DEFAULT (' ') NOT NULL,
    [Clave_Indicador]          VARCHAR (255) DEFAULT (' ') NOT NULL,
    [AccionInstitucional]      VARCHAR (255) DEFAULT (' ') NOT NULL,
    [NombreIndicador]          VARCHAR (255) DEFAULT (' ') NOT NULL,
    [MetodoCalculo]            VARCHAR (255) DEFAULT (' ') NOT NULL,
    [IndicadorMeta2024]        VARCHAR (255) DEFAULT (' ') NOT NULL,
    [PRIMER_TRIM]              VARCHAR (255) DEFAULT (' ') NOT NULL,
    [SEGUNDO_TRIM]             VARCHAR (255) DEFAULT (' ') NOT NULL,
    [TERCER_TRIM]              VARCHAR (255) DEFAULT (' ') NOT NULL,
    [CUARTO_TRIM]              VARCHAR (255) DEFAULT (' ') NOT NULL,
    [PRIMER_TRIMV2]            VARCHAR (255) DEFAULT (' ') NOT NULL,
    [SEGUNDO_TRIMV2]           VARCHAR (255) DEFAULT (' ') NOT NULL,
    [TERCER_TRIMV2]            VARCHAR (255) DEFAULT (' ') NOT NULL,
    [CUARTO_TRIMV2]            VARCHAR (255) DEFAULT (' ') NOT NULL,
    [Fecha]                    VARCHAR (255) DEFAULT (' ') NOT NULL,
    [id_DependenciasEvaluadas] INT           NULL,
    [id_Usuario]               INT           NULL,
    [id_Trimestre]             INT           NULL,
    [id_Anio]                  INT           NULL,
    PRIMARY KEY CLUSTERED ([ID_FAES_IndicadoresExtra] ASC),
    FOREIGN KEY ([id_Anio]) REFERENCES [dbo].[Anio] ([ID_Anio]),
    FOREIGN KEY ([id_DependenciasEvaluadas]) REFERENCES [dbo].[Dependencias_Evaluadas] ([ID_DependenciasEvaluadas]),
    FOREIGN KEY ([id_Trimestre]) REFERENCES [dbo].[Trimestre] ([ID_Trimestre]),
    FOREIGN KEY ([id_Usuario]) REFERENCES [dbo].[Usuario_General] ([ID_Usuario])
);

