CREATE PROCEDURE DFLE_MuestraTipoUnidadAcademica
AS 
BEGIN
    SELECT 'NIVEL MEDIO SUPERIOR' AS TipoUnidadAcademica UNION ALL
    SELECT 'NIVEL SUPERIOR' UNION ALL
    SELECT 'UNIDADES ACADÉMICAS DE INVESTIGACIÓN CIENTÍFICA Y TECNOLÓGICA' UNION ALL
    SELECT 'UNIDADES ACADÉMICAS DE VINCULACION Y DESARROLLO REGIONAL' UNION ALL
    SELECT 'UNIDADES ACADÉMICAS DE INNOVACION E INTEGRACION DE TECNOLOGÍAS AVANZADAS' UNION ALL
    SELECT 'UNIDADES ACADÉMICAS DE APOYO EDUCATIVO' UNION ALL
    SELECT 'TOTAL' ;
END
